Add Nav
cosola-macile/practicar-pull-requests pull request #2
Opened 2017-06-06 20:14 UTC by YaArias

Se agrego navegador en index.html y se modifico el css.

### Issues

¿Qué se está resolviendo?
*Estamos resolviendo el nav*
### Todos

¿Qué queda por hacer?
*Revisar y terminar*
### Áreas impactadas

¿Qué páginas o componentes están afectados?
*index.html y main.css*
### Pasos para reproducir

¿Qué necesitamos hacer para probar?
--

2017-06-06 20:27 UTC, misscs requested changes

2017-06-06 20:27 UTC, misscs commented on css/main.css
> +#left{
No se debe usar IDs para aplicar CSS. Utiliza una classe or pseudo-selector.

```
.nav li:last-child {
  margin-left: 700px;
}

```
Segunda problema, si añadimos outro link hay que cambiar el CSS. Hay dos maneras para resolver la problema: usando floats o flexbox.

2017-06-06 20:27 UTC, misscs commented on css/main.css
>  }
You want to strive for consistency in the file. Make sure the same amount of spacing is used

2017-06-06 20:27 UTC, misscs commented on css/main.css
> +li{
Es costumbre tener un espacio antes de `{`

2017-06-06 20:27 UTC, misscs commented on index.html
> +
Este código debe estar en el `body`

2017-06-06 20:27 UTC, misscs commented on index.html
> +			<li id="left"><a href="">About</li></a>
Alinear con el `li` de arriba

2017-06-06 21:43 UTC, YaArias reviewed
Hemos tenido algunos problemas, ma;ana con mas tiempo le arreglaremos.

Gracias :)

2017-06-07 18:26 UTC, misscs requested changes

2017-06-07 18:26 UTC, misscs commented on index.html
> +	<nav>
El `div` no es necessario cuando usan `nav`. Pueden mover la classes `menu` en el `nav`

2017-06-07 18:26 UTC, misscs commented on index.html
> +			</nav>
Spacing :) No está aliñada con el contenido del body. 👀 en lalíneaa 35.

2017-06-07 18:26 UTC, misscs commented on index.html
> +			<nav class="menu">
💯

2017-06-07 18:26 UTC, misscs commented on index.html
> +					<li class="menu-li-home"><a href="">Home</a></li>
Muy bien hecho creado esta nueva classe! Deben de usar las dos clases asi no tiene que copiar los estilos.

2017-06-07 18:26 UTC, misscs commented on css/main.css
> +}
No hay razón de duplicar los estilos de `menu-li` en `.menu-li-home`

2017-06-07 18:26 UTC, misscs commented on css/main.css
> +ul{
Tengan mucho cuidado con los espacios. Siempre deben de tener un espacio antes des `{`

2017-06-07 19:11 UTC, misscs submitted a review, later dismissed
💯 💃 🎉

2017-06-07 19:15 UTC, misscs approved these changes

2017-06-07 19:15 UTC, merged