Add footer
cosola-macile/practicar-pull-requests pull request #3
Opened 2017-06-06 20:32 UTC by Morban15

Adding sticky footer

### Issues

¿Qué se está resolviendo?
Agregando footer a la página

### Todos

¿Qué queda por hacer?
Revisar y terminar
### Áreas impactadas

¿Qué páginas o componentes están afectados?
index.html, main.css
### Pasos para reproducir

¿Qué necesitamos hacer para probar?

2017-06-06 20:36 UTC, misscs commented
Deben usar flexbox para resolver este problema

2017-06-06 21:41 UTC, Morban15 commented
No hemos concluido, llegaremos temprano para poder concluir.

2017-06-07 12:57 UTC, misscs commented
Estay bien! Pueden abrir el pull request antes de terminar. 👍

2017-06-07 18:33 UTC, misscs requested changes
💯 🎉Excelentete trabajo con flexbox! Mis revisiones son puramente sintaxis y estilo

2017-06-07 18:33 UTC, misscs commented on index.html
> +		</div>
El `footer` debe de ir arriba de los scripts. También, hay una etiqueta más semantica  `footer`.

2017-06-07 18:33 UTC, misscs commented on index.html
>          <p>Hola Mundo This is HTML5 Boilerplate.</p>
Este contenido debe de estar dentro del wrapper, no? El wrapper esta funcionado como el contenedor del contenido, verdad?

2017-06-07 18:33 UTC, misscs commented on index.html
> +		</div>
Asegurense que todo esta aliñado siguiendo el estilo del documento.

2017-06-07 18:33 UTC, misscs commented on css/main.css
> +.wrapper{
Siempre usamos un espacio antes del `{`

2017-06-07 18:59 UTC, misscs approved these changes
💯 💃 Muy bien!! 

Mi unica comentario final seria que deben de prestar atención as los mensajes de commit. El titulo debe de describir el cambio.

2017-06-07 19:08 UTC, merged